blank_issues_enabled: false
contact_links:
  - name: Rock Community Chat
    url: https://community.rockrms.com/chat
    about: Questions? Join the #mobile channel.
  - name: Feature Requests
    url: https://community.rockrms.com/Ideas
    about: Submit ideas with Domain set to Mobile.
